### ISSUE TITLE
UTF-8 should be default in any project past 2010

### ISSUE THREAD

**Issue by PofMagicfingers** [misnard/Podcast-rss-generator-from-folder#14]
https://github.com/misnard/Podcast-rss-generator-from-folder/blob/22cc7c856bb0f319811793830c77e76d1b8df113/rss-dependencies/template.xsl#L3

**Comment by PofMagicfingers** [comment]
Sorry duplicate of #12

**Comment by PhilGoud** [comment]
bien ouej

connard
